# Generated by Django 5.2.9 on 2025-12-31 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('bio', models.TextField(null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('profile_image', models.ImageField(blank=True, default='portfolio/empty.png', upload_to='portfolio')),
                ('social_github', models.CharField(blank=True, max_length=300)),
                ('social_telegram', models.CharField(blank=True, max_length=300)),
                ('social_instagram', models.CharField(blank=True, max_length=300)),
                ('social_youtube', models.CharField(blank=True, max_length=300)),
                ('social_website', models.CharField(blank=True, max_length=300)),
                ('created', models.DateField(auto_now_add=True)),
                ('file', models.FileField(default=None, null=True, upload_to='files')),
                ('video', models.FileField(default=None, null=True, upload_to='videos')),
                ('audio', models.FileField(default=None, null=True, upload_to='audios')),
                ('rezyume', models.FileField(null=True, upload_to='files')),
                ('users', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
